# Generated by Django 3.0.6 on 2020-08-30 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('IDNumber', models.CharField(default='ID Number', max_length=30, null=True)),
                ('Designation', models.CharField(blank=True, default='JE/C&W/TKD', max_length=30, null=True)),
                ('Posted', models.CharField(blank=True, choices=[('TKD Sickline Office', 'TKD Sickline Office'), ('TKD ROH Office', 'TKD ROH'), ('TKD SSE Planning Office', 'TKD SSE Planning Office'), ('TKD M&P Section', 'TKD M&P Section'), ('TKD Administration', 'TKD Administration'), ('TKD Stores', 'TKD Stores'), ('TKD Wheel Lathe', 'TKD Wheel Lathe'), ('TKD Train Duty Office', 'TKD Train Duty Office'), ('TKD ICD', 'TKD ICD')], default='TKD Administration', max_length=30, null=True)),
                ('DateOfJoining', models.DateField(blank=True, default='1001-01-01', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
