# Generated by Django 3.0.8 on 2020-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DateOfJoining',
            field=models.DateField(blank=True, default='1001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Designation',
            field=models.CharField(blank=True, default='JE/C&W/TKD', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='IDNumber',
            field=models.CharField(default='ID Number', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Posted',
            field=models.CharField(blank=True, choices=[('TKD Sickline Office', 'TKD Sickline Office'), ('TKD ROH Office', 'TKD ROH'), ('TKD SSE Planning Office', 'TKD SSE Planning Office'), ('TKD M&P Section', 'TKD M&P Section'), ('TKD Administration', 'TKD Administration'), ('TKD Stores', 'TKD Stores'), ('TKD Wheel Lathe', 'TKD Wheel Lathe'), ('TKD Train Duty Office', 'TKD Train Duty Office'), ('TKD ICD', 'TKD ICD')], default='TKD Administration', max_length=30, null=True),
        ),
    ]
