# Generated by Django 3.0.6 on 2020-09-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='LocalAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
