# Generated by Django 3.0.8 on 2020-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon1ROHDate',
            field=models.DateField(default='1000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon2ROHDate',
            field=models.DateField(default='1000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon3ROHDate',
            field=models.DateField(default='1000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon4ROHDate',
            field=models.DateField(default='1000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon5ROHDate',
            field=models.DateField(default='1000-01-01', null=True),
        ),
    ]
