# Generated by Django 3.0.8 on 2020-08-30 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sidingz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulerecieved',
            name='ModuleDVSDateTime',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon1ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon2ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon3ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon4ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon5ROHDate',
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ModuleCommDate',
            field=models.DateField(blank=True, default='1001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ModuleDVR',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ModuleDVSDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ModulePOHDate',
            field=models.DateField(blank=True, default='1001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ModuleROHDate',
            field=models.DateField(blank=True, default='1001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='POHStation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ROHStation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='LineNumber',
            field=models.CharField(blank=True, choices=[('SELECTLINE', 'Please Select Examination Line'), ('NH1', 'NH1'), ('NH2', 'NH2'), ('NH3', 'NH3'), ('NH4', 'NH4'), ('NH5', 'NH5'), ('NH6', 'NH6'), ('NH7', 'NH7')], default='SELECTLINE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleDVS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleMadeFit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleMadeFitDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModulePresentPosition',
            field=models.CharField(choices=[('TKD_ACTL', 'TKD ACTL'), ('TKD_HTPP_PWL', 'TKD HTPP PWL'), ('TKD_ICD', 'TKD ICD'), ('TKD_YARD', 'TKD YARD'), ('SSB_ICD_GHH', 'SSB ICD GHH'), ('SSB_ICD_PT', 'SSB ICD PTT'), ('GZB_ICD_NOLI', 'GZB ICD NOLI'), ('GZB_ICD_MUZ', 'GZB ICD MUZ'), ('PNP_BMDJ', 'PNP BMDJ'), ('PNP_PCWD_DWNA', 'PNP PCWD DWNA')], default='YARD', max_length=13),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleRecieveDate',
            field=models.DateField(default='1001-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon1Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon2Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon3Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon4Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon5Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
