# Generated by Django 3.0.8 on 2020-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0003_auto_20200809_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='LineNumber',
            field=models.CharField(blank=True, choices=[('SELECTLINE', 'Please Select Examination Line'), ('NH1', 'NH1'), ('NH2', 'NH2'), ('NH3', 'NH3'), ('NH4', 'NH4'), ('NH5', 'NH5'), ('NH6', 'NH6'), ('NH7', 'NH7')], default='SELECTLINE', max_length=10, null=True),
        ),
    ]
