# Generated by Django 3.0.8 on 2020-09-03 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sidingz', '0004_auto_20200830_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerecieved',
            name='ROHFile',
            field=models.FileField(blank=True, null=True, upload_to='ROH/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='RakeNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon1Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon1Type',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon2Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon2Type',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon3Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon3Type',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon4Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon4Type',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon5Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon5Type',
            field=models.CharField(blank=True, choices=[('SelectWagon', 'Please Select Wagon Type'), ('BOXN', 'BOXN'), ('BOXNHA', 'BOXNHA'), ('BOXNHS', 'BOXNHS'), ('BOXNCR', 'BOXNCR'), ('BOXNLW', 'BOXNLW'), ('BOXNB', 'BOXNB'), ('BOXNF', 'BOXNF'), ('BOXNG', 'BOXNG'), ('BOY', 'BOY'), ('BOST', 'BOST'), ('BOXNAL', 'BOXNAL'), ('BOSTHS', 'BOSTHS'), ('BOXNHL', 'BOXNHL'), ('BOXNAL', 'BOXNAL'), ('BOXNS', 'BOXNS'), ('BCN', 'BCN'), ('BCNA', 'BCNA'), ('BCNAHS', 'BCNAHS'), ('BCCNR', 'BCCNR'), ('BTPN', 'BTPN'), ('BTPNHS', 'BTPNHS'), ('BTPGLN', 'BTPGLN'), ('BTALN', 'BTALN'), ('BTCS', 'BTCS'), ('BTPH', 'BTPH'), ('BTAP', 'BTAP'), ('BTFLN', 'BTFLN'), ('BRNA', 'BRNA'), ('BRNAHS', 'BRNAHS'), ('BFNS', 'BFNS'), ('BOMN', 'BOMN'), ('BRSTH', 'BRSTH'), ('BFAT', 'BFAT'), ('BLCA', 'BLCA'), ('BLCB', 'BLCB'), ('BLLA', 'BLLA'), ('BLLB', 'BLLB'), ('BRS', 'BRS'), ('BFU', 'BFU'), ('BRHNEHS', 'BRHNEHS'), ('BCL', 'BCL'), ('BCLA', 'BCLA'), ('BOBYN', 'BOBYN'), ('BOBYNHS', 'BOBYNHS'), ('BOBRN', 'BOBRN'), ('BOBRNHS', 'BOBRNHS'), ('BOBRAL', 'BOBRAL'), ('BOBSN', 'BOBSN'), ('BWTB', 'BWTB'), ('MBWT', 'MBWT'), ('DBKM', 'DBKM'), ('MBWZ', 'MBWZ'), ('BVZC', 'BVZC'), ('BVZI', 'BVZI'), ('BFKHN', 'BFKHN')], default='SelectWagon', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
