# Generated by Django 3.0.8 on 2020-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0005_auto_20200903_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModulePresentPosition',
            field=models.CharField(choices=[('TKD_ROH1', 'TKD ROH 1'), ('TKD_ROH2', 'TKD ROH 2'), ('TKD_Sickline', 'TKD Sickline'), ('TKD_ACTL', 'TKD ACTL'), ('TKD_HTPP_PWL', 'TKD HTPP PWL'), ('TKD_ICD', 'TKD ICD'), ('TKD_YARD', 'TKD YARD'), ('SSB_ICD_GHH', 'SSB ICD GHH'), ('SSB_ICD_PT', 'SSB ICD PTT'), ('GZB_ICD_NOLI', 'GZB ICD NOLI'), ('GZB_ICD_MUZ', 'GZB ICD MUZ'), ('PNP_BMDJ', 'PNP BMDJ'), ('PNP_PCWD_DWNA', 'PNP PCWD DWNA')], default='YARD', max_length=13),
        ),
    ]
