# Generated by Django 3.0.8 on 2020-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0005_auto_20200810_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulerecieved',
            old_name='Wagon1ROHDate',
            new_name='ModuleROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='ModuleDVSDateTime',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon2ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon3ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon4ROHDate',
        ),
        migrations.RemoveField(
            model_name='modulerecieved',
            name='Wagon5ROHDate',
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ModuleDVSDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModulePresentPosition',
            field=models.CharField(choices=[('TKD_ACTL', 'TKD ACTL'), ('TKD_HTPP_PWL', 'TKD HTPP PWL'), ('TKD_ICD', 'TKD ICD'), ('TKD_YARD', 'TKD YARD'), ('SSB_ICD_GHH', 'SSB ICD GHH'), ('SSB_ICD_PT', 'SSB ICD PT'), ('GZB_ICD_NOLI', 'GZB ICD NOLI'), ('GZB_ICD_MUZ', 'GZB ICD MUZ'), ('PNP_BMDJ', 'PNP BMDJ'), ('PNP_PCWD_DWNA', 'PNP PCWD DWNA')], default='YARD', max_length=13),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon1Defect',
            field=models.CharField(blank=True, default='1000-01-01', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon2Defect',
            field=models.CharField(blank=True, default='1000-01-01', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon3Defect',
            field=models.CharField(blank=True, default='1000-01-01', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon4Defect',
            field=models.CharField(blank=True, default='1000-01-01', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon5Defect',
            field=models.CharField(blank=True, default='1000-01-01', max_length=100, null=True),
        ),
    ]
