# Generated by Django 3.2.6 on 2021-08-18 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sidingz', '0006_auto_20200904_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='LineNumber',
            field=models.CharField(blank=True, choices=[('SELECTLINE', 'Please Select Examination Line'), ('NH1', 'NH1'), ('NH2', 'NH2'), ('NH4', 'NH4'), ('NH5', 'NH5'), ('NH6', 'NH6'), ('NH7', 'NH7'), ('NH8', 'NH8')], default='SELECTLINE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sid', to=settings.AUTH_USER_MODEL),
        ),
    ]
