# Generated by Django 3.0.8 on 2020-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0006_auto_20200811_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleDVSDate',
            field=models.DateField(default='1000-01-01', null=True),
        ),
    ]
