# Generated by Django 3.0.8 on 2020-08-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0007_auto_20200811_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleDVSDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon1Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon2Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon3Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon4Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='Wagon5Defect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
