# Generated by Django 3.0.8 on 2020-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0008_auto_20200811_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleROHDate',
            field=models.DateField(default='1001-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleRecieveDate',
            field=models.DateField(default='1001-01-01', null=True),
        ),
    ]
