# Generated by Django 3.0.6 on 2020-08-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0005_auto_20200810_0936'),
        ('sidingz', '0009_auto_20200811_2031'),
    ]

    operations = [
    ]
