# Generated by Django 3.0.6 on 2020-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0010_merge_20200815_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModulePresentPosition',
            field=models.CharField(choices=[('TKD_ACTL', 'TKD ACTL'), ('TKD_HTPP_PWL', 'TKD HTPP PWL'), ('TKD_ICD', 'TKD ICD'), ('TKD_YARD', 'TKD YARD'), ('SSB_ICD_GHH', 'SSB ICD GHH'), ('SSB_ICD_PT', 'SSB ICD PT'), ('GZB_ICD_NOLI', 'GZB ICD NOLI'), ('GZB_ICD_MUZ', 'GZB ICD MUZ'), ('PNP_BMDJ', 'PNP BMDJ'), ('PNP_PCWD_DWNA', 'PNP PCWD DWNA')], default='YARD', max_length=13),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleROHDate',
            field=models.DateField(blank=True, default='1001-01-01', null=True),
        ),
    ]
