# Generated by Django 3.0.6 on 2020-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidingz', '0012_auto_20200825_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerecieved',
            name='ModuleDVR',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='POHStation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modulerecieved',
            name='ROHStation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleDVS',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleDVSDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulerecieved',
            name='ModuleMadeFit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
