# Generated by Django 3.0.8 on 2020-09-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200905_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentfile',
            field=models.FileField(blank=True, null=True, upload_to='uploadsblogcomment/%Y/%m/%d/'),
        ),
    ]
