# Generated by Django 3.0.8 on 2020-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0002_auto_20200905_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnppost',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploadsMnp/%Y/%m/%d/'),
        ),
    ]
