# Generated by Django 3.0.8 on 2020-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnp', '0004_auto_20200905_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnpcomment',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploadsMnpComments/%Y/%m/%d/'),
        ),
    ]
