# Generated by Django 3.0.5 on 2020-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='registerWheelDispatchedJudw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True)),
                ('TruckNo', models.CharField(max_length=12)),
                ('BLC', models.IntegerField()),
                ('BCN', models.IntegerField()),
                ('ICF', models.IntegerField()),
                ('Remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='registerWheelRecievedJudw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True)),
                ('TruckNo', models.CharField(max_length=12)),
                ('BLC', models.IntegerField()),
                ('BCN', models.IntegerField()),
                ('ICF', models.IntegerField()),
                ('Remark', models.TextField()),
            ],
        ),
    ]
