# Generated by Django 3.0.5 on 2020-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerHotAxle_Wagon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDetached', models.DateTimeField(blank=True)),
                ('Station', models.CharField(max_length=5)),
                ('Section', models.CharField(max_length=5)),
                ('WagonNumber', models.BigIntegerField()),
                ('Railway', models.CharField(max_length=5)),
                ('Class', models.CharField(max_length=5)),
                ('TruckNo', models.CharField(max_length=12)),
                ('WheelRecieveDate', models.DateTimeField()),
                ('Remark', models.TextField()),
            ],
        ),
    ]
