# Generated by Django 3.0.5 on 2020-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROH', '0002_registerhotaxle_wagon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerwheelrecievedjudw',
            name='Date',
            field=models.DateField(blank=True),
        ),
    ]
