# Generated by Django 3.0.5 on 2020-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROH', '0003_auto_20200424_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerwheeldispatchedjudw',
            name='Date',
            field=models.DateField(blank=True),
        ),
    ]
