# Generated by Django 3.0.5 on 2020-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROH', '0006_auto_20200424_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerGaugeCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50)),
                ('IMTENumber', models.CharField(max_length=15)),
                ('NextCalibrationDue', models.DateField()),
            ],
        ),
    ]
