# Generated by Django 3.0.8 on 2020-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p',
            name='MAC',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
