# Generated by Django 3.0.1 on 2020-05-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerCurrentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100, unique=True)),
                ('PL_Number', models.BigIntegerField(unique=True)),
                ('Stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registerStockRecieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockRecieved', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores_registerstockrecieved_item', to='stores.registerCurrentStock', to_field='Item')),
                ('pl_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores_registerstockrecieved_pl_number', to='stores.registerCurrentStock', to_field='PL_Number')),
            ],
        ),
    ]
