# Generated by Django 3.0.1 on 2020-05-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200523_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerStockDispatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PL_Number', models.IntegerField()),
                ('stockDispatched', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.registerCurrentStock')),
            ],
        ),
    ]
