# Generated by Django 3.0.1 on 2020-05-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_registerstockdispatched'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerStockDispatched',
            new_name='registerStockDispatchedROH',
        ),
    ]
