# Generated by Django 3.0.1 on 2020-05-24 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_registerstockdispatchedsickline'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercurrentstock',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registerstockdispatchedroh',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registerstockdispatchedsickline',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registerstockrecieved',
            name='updateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
