# Generated by Django 3.0.6 on 2020-05-26 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200524_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerStockDispatchedYard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PL_Number', models.IntegerField()),
                ('stockDispatched', models.IntegerField()),
                ('Yard', models.CharField(choices=[('ACTL', 'ACTL'), ('HTPP', 'HTPP'), ('ICD_TKD', 'ICD_TKD'), ('ICD', 'ICD')], default='ACTL', max_length=7)),
                ('updateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.registerCurrentStock')),
            ],
        ),
        migrations.CreateModel(
            name='registerStockDispatchedTrainDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PL_Number', models.IntegerField()),
                ('stockDispatched', models.IntegerField()),
                ('updateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.registerCurrentStock')),
            ],
        ),
    ]
