# Generated by Django 3.0.6 on 2020-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_registerstockdispatchedtrainduty_registerstockdispatchedyard'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercurrentstock',
            name='AAC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registerstockrecieved',
            name='AAC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registerstockrecieved',
            name='stockRecievedChoices',
            field=models.CharField(choices=[('AMM', 'AMM'), ('JAGADHRI', 'JAGADHRI'), ('SHAKURBASTI', 'SHAKURBASTI')], default='AMM', max_length=11),
        ),
    ]
