# Generated by Django 3.0.6 on 2020-08-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20200527_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstockdispatchedroh',
            name='Item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerstockdispatchedsickline',
            name='Item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerstockdispatchedtrainduty',
            name='Item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerstockdispatchedyard',
            name='Item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerstockrecieved',
            name='Item',
            field=models.CharField(max_length=100),
        ),
    ]
