# Generated by Django 3.0.8 on 2020-08-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20200809_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstockrecieved',
            name='Item',
            field=models.CharField(max_length=100),
        ),
    ]
