# Generated by Django 3.0.8 on 2020-08-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20200809_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstockdispatchedsickline',
            name='Item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerstockdispatchedtrainduty',
            name='Item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registerstockdispatchedyard',
            name='Item',
            field=models.CharField(max_length=100),
        ),
    ]
