# Generated by Django 3.0.6 on 2020-08-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20200809_0954'),
        ('stores', '0009_auto_20200809_1012'),
    ]

    operations = [
    ]
